# resultats_norme_moi = [['Mot', 'Henry'], ['Lemme', 'Henry'], ['POS', 'PROPN']]
# [['Mot', 'William'], ['Lemme', 'William'], ['POS', 'PROPN']]
# [['Mot', 'Dalgliesh'], ['Lemme', 'Dalgliesh'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'né'], ['Lemme', 'naître'], ['POS', 'VERB']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', '5'], ['Lemme', '5'], ['POS', 'NUM']]
# [['Mot', 'mai'], ['Lemme', 'mai'], ['POS', 'NOUN']]
# [['Mot', '1983'], ['Lemme', '1983'], ['POS', 'NUM']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'Saint-Hélier'], ['Lemme', 'Saint-Hélier'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'est'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'un'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'acteur'], ['Lemme', 'acteur'], ['POS', 'NOUN']]
# [['Mot', 'britannique'], ['Lemme', 'britannique'], ['POS', 'ADJ']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'Il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'est'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'principalement'], ['Lemme', 'principalement'], ['POS', 'ADV']]
# [['Mot', 'connu'], ['Lemme', 'connaître'], ['POS', 'VERB']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'son'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'rôle'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Charles'], ['Lemme', 'Charles'], ['POS', 'PROPN']]
# [['Mot', 'Brandon'], ['Lemme', 'Brandon'], ['POS', 'PROPN']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'Les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Tudors'], ['Lemme', 'tudor'], ['POS', 'NOUN']]
# [['Mot', 'puis'], ['Lemme', 'puis'], ['POS', 'CCONJ']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Superman'], ['Lemme', 'Superman'], ['POS', 'PROPN']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'cinq'], ['Lemme', 'cinq'], ['POS', 'NUM']]
# [['Mot', 'films'], ['Lemme', 'film'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'univers'], ['Lemme', 'univers'], ['POS', 'NOUN']]
# [['Mot', 'cinématographique'], ['Lemme', 'cinématographique'], ['POS', 'ADJ']]
# [['Mot', 'DC'], ['Lemme', 'DC'], ['POS', 'PROPN']]
# [['Mot', ':'], ['Lemme', ':'], ['POS', 'PUNCT']]
# [['Mot', 'Man'], ['Lemme', 'man'], ['POS', 'NOUN']]
# [['Mot', 'of'], ['Lemme', 'of'], ['POS', 'ADP']]
# [['Mot', 'Steel'], ['Lemme', 'Steel'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', '2013'], ['Lemme', '2013'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Batman'], ['Lemme', 'Batman'], ['POS', 'PROPN']]
# [['Mot', 'v'], ['Lemme', 'v'], ['POS', 'AUX']]
# [['Mot', 'Superman'], ['Lemme', 'Superman'], ['POS', 'PROPN']]
# #[['Mot', ':'], ['Lemme', ':'], ['POS', 'PUNCT']]
# [['Mot', "L'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Aube'], ['Lemme', 'aube'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'la'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'justice'], ['Lemme', 'justice'], ['POS', 'NOUN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', '2016'], ['Lemme', '2016'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Justice'], ['Lemme', 'justice'], ['POS', 'NOUN']]
# [['Mot', 'League'], ['Lemme', 'league'], ['POS', 'NOUN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', '2017'], ['Lemme', '2017'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Zack'], ['Lemme', 'Zack'], ['POS', 'PROPN']]
# [['Mot', "Snyder'"], ['Lemme', "snyder'"], ['POS', 'PROPN']]
# [['Mot', 's'], ['Lemme', 's'], ['POS', 'PRON']]
# [['Mot', 'Justice'], ['Lemme', 'Justice'], ['POS', 'PROPN']]
# [['Mot', 'League'], ['Lemme', 'League'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', '2021'], ['Lemme', '2021'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'Black'], ['Lemme', 'Black'], ['POS', 'PROPN']]
# [['Mot', 'Adam'], ['Lemme', 'Adam'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', '2022'], ['Lemme', '2022'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'dont'], ['Lemme', 'dont'], ['POS', 'PRON']]
# [['Mot', 'trois'], ['Lemme', 'trois'], ['POS', 'NUM']]
# [['Mot', 'réalisés'], ['Lemme', 'réaliser'], ['POS', 'VERB']]
# [['Mot', 'par'], ['Lemme', 'par'], ['POS', 'ADP']]
# [['Mot', 'Zack'], ['Lemme', 'Zack'], ['POS', 'PROPN']]
# [['Mot', 'Snyder'], ['Lemme', 'Snyder'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'incarne'], ['Lemme', 'incarner'], ['POS', 'VERB']]
# [['Mot', 'aussi'], ['Lemme', 'aussi'], ['POS', 'ADV']]
# [['Mot', 'Sherlock'], ['Lemme', 'Sherlock'], ['POS', 'PROPN']]
# [['Mot', 'Holmes'], ['Lemme', 'Holmes'], ['POS', 'PROPN']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'films'], ['Lemme', 'film'], ['POS', 'NOUN']]
# [['Mot', 'Netflix'], ['Lemme', 'Netflix'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Enola'], ['Lemme', 'Enola'], ['POS', 'PROPN']]
# [['Mot', 'Holmes'], ['Lemme', 'Holmes'], ['POS', 'PROPN']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'Enola'], ['Lemme', 'Enola'], ['POS', 'PROPN']]
# [['Mot', 'Holmes'], ['Lemme', 'Holmes'], ['POS', 'PROPN']]
# [['Mot', '2'], ['Lemme', '2'], ['POS', 'NUM']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'respectivement'], ['Lemme', 'respectivement'], ['POS', 'ADV']]
# [['Mot', 'sortis'], ['Lemme', 'sortir'], ['POS', 'VERB']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '2020'], ['Lemme', '2020'], ['POS', 'NUM']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', '2022'], ['Lemme', '2022'], ['POS', 'NUM']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'De'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', '2019'], ['Lemme', '2019'], ['POS', 'NUM']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', '2023'], ['Lemme', '2023'], ['POS', 'NUM']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'est'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'interprète'], ['Lemme', 'interprète'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Geralt'], ['Lemme', 'Geralt'], ['POS', 'PROPN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Riv'], ['Lemme', 'Riv'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'personnage'], ['Lemme', 'personnage'], ['POS', 'NOUN']]
# [['Mot', 'principal'], ['Lemme', 'principal'], ['POS', 'ADJ']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'la'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'série'], ['Lemme', 'série'], ['POS', 'NOUN']]
# [['Mot', 'The'], ['Lemme', 'The'], ['POS', 'X']]
# [['Mot', 'Witcher'], ['Lemme', 'Witcher'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'diffusée'], ['Lemme', 'diffuser'], ['POS', 'VERB']]
# [['Mot', 'sur'], ['Lemme', 'sur'], ['POS', 'ADP']]
# [['Mot', 'Netflix'], ['Lemme', 'Netflix'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n'], ['Lemme', '\n'], ['POS', 'SPACE']]
# [['Mot', 'Biographie'], ['Lemme', 'biographie'], ['POS', 'NOUN']]
# [['Mot', '\n'], ['Lemme', '\n'], ['POS', 'SPACE']]
# [['Mot', 'Jeunesse'], ['Lemme', 'Jeunesse'], ['POS', 'PROPN']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'formation'], ['Lemme', 'formation'], ['POS', 'NOUN']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'Originaire'], ['Lemme', 'originaire'], ['POS', 'ADJ']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Jersey'], ['Lemme', 'Jersey'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'îles'], ['Lemme', 'île'], ['POS', 'ADJ']]
# [['Mot', 'anglo-normandes'], ['Lemme', 'anglo-normand'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Henry'], ['Lemme', 'Henry'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', 'y'], ['Lemme', 'y'], ['POS', 'PRON']]
# [['Mot', 'a'], ['Lemme', 'avoir'], ['POS', 'VERB']]
# [['Mot', 'grandi'], ['Lemme', 'grandir'], ['POS', 'VERB']]
# [['Mot', 'avec'], ['Lemme', 'avec'], ['POS', 'ADP']]
# [['Mot', 'ses'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'deux'], ['Lemme', 'deux'], ['POS', 'NUM']]
# [['Mot', 'parents'], ['Lemme', 'parent'], ['POS', 'NOUN']]
# [['Mot', ';'], ['Lemme', ';'], ['POS', 'PUNCT']]
# [['Mot', 'Marianne'], ['Lemme', 'marianne'], ['POS', 'NOUN']]
# [['Mot', 'Dalgliesh'], ['Lemme', 'Dalgliesh'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'secrétaire'], ['Lemme', 'secrétaire'], ['POS', 'NOUN']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'une'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'banque'], ['Lemme', 'banque'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'origine'], ['Lemme', 'origine'], ['POS', 'NOUN']]
# [['Mot', 'irlandaise'], ['Lemme', 'irlandais'], ['POS', 'ADJ']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'écossaise'], ['Lemme', 'écossais'], ['POS', 'ADJ']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'anglaise'], ['Lemme', 'anglaise'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'Colin'], ['Lemme', 'Colin'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'agent'], ['Lemme', 'agent'], ['POS', 'ADV']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'change'], ['Lemme', 'change'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'originaire'], ['Lemme', 'originaire'], ['POS', 'ADJ']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Chester1'], ['Lemme', 'chester1'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'ainsi'], ['Lemme', 'ainsi'], ['POS', 'ADV']]
# [['Mot', "qu'"], ['Lemme', 'que'], ['POS', 'SCONJ']]
# [['Mot', 'avec'], ['Lemme', 'avec'], ['POS', 'ADP']]
# [['Mot', 'ses'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'quatre'], ['Lemme', 'quatre'], ['POS', 'NUM']]
# [['Mot', 'frères'], ['Lemme', 'frère'], ['POS', 'NOUN']]
# [['Mot', ';'], ['Lemme', ';'], ['POS', 'PUNCT']]
# [['Mot', 'Piers'], ['Lemme', 'Piers'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Niki'], ['Lemme', 'Niki'], ['POS', 'PROPN']]
# [['Mot', 'Richard'], ['Lemme', 'Richard'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'né'], ['Lemme', 'naître'], ['POS', 'VERB']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '1975'], ['Lemme', '1975'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Simon'], ['Lemme', 'Simon'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'né'], ['Lemme', 'naître'], ['POS', 'VERB']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '1979'], ['Lemme', '1979'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'Charlie'], ['Lemme', 'Charlie'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'né'], ['Lemme', 'naître'], ['POS', 'VERB']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '1988'], ['Lemme', '1988'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'est'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'issu'], ['Lemme', 'issu'], ['POS', 'VERB']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'une'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'famille'], ['Lemme', 'famille'], ['POS', 'NOUN']]
# [['Mot', 'catholique'], ['Lemme', 'catholique'], ['POS', 'ADJ']]
# [['Mot', 'romaine2'], ['Lemme', 'romaine2'], ['POS', 'ADJ']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'étudie'], ['Lemme', 'étudier'], ['POS', 'VERB']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'la'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'St.'], ['Lemme', 'st.'], ['POS', 'NOUN']]
# [['Mot', 'Michael’'], ['Lemme', 'michael’'], ['POS', 'ADJ']]
# [['Mot', 's'], ['Lemme', 's'], ['POS', 'PRON']]
# [['Mot', 'Preparatory'], ['Lemme', 'preparatory'], ['POS', 'VERB']]
# [['Mot', 'School'], ['Lemme', 'School'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'NOUN']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Saint-Sauveur'], ['Lemme', 'Saint-Sauveur'], ['POS', 'PROPN']]
# [['Mot', 'avant'], ['Lemme', 'avant'], ['POS', 'ADP']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'intégrer'], ['Lemme', 'intégrer'], ['POS', 'VERB']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'internat'], ['Lemme', 'internat'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'la'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Stowe'], ['Lemme', 'Stowe'], ['POS', 'PROPN']]
# [['Mot', 'School'], ['Lemme', 'School'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'NOUN']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Buckingham'], ['Lemme', 'Buckingham'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'où'], ['Lemme', 'où'], ['POS', 'PRON']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'fait'], ['Lemme', 'faire'], ['POS', 'VERB']]
# [['Mot', 'ses'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'premières'], ['Lemme', 'premier'], ['POS', 'ADJ']]
# [['Mot', 'gammes'], ['Lemme', 'gamme'], ['POS', 'NOUN']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', 'tant'], ['Lemme', 'tant'], ['POS', 'ADV']]
# [['Mot', "qu'"], ['Lemme', 'que'], ['POS', 'SCONJ']]
# [['Mot', 'acteur'], ['Lemme', 'acteur'], ['POS', 'NOUN']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'souffre'], ['Lemme', 'souffre'], ['POS', 'NOUN']]
# [['Mot', 'des'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'moqueries'], ['Lemme', 'moquerie'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'ses'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'camarades'], ['Lemme', 'camarade'], ['POS', 'NOUN']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'cause'], ['Lemme', 'cause'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'son'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'embonpoint'], ['Lemme', 'embonpoint'], ['POS', 'NOUN']]
# [['Mot', ';'], ['Lemme', ';'], ['POS', 'PUNCT']]
# [['Mot', 'ces'], ['Lemme', 'ce'], ['POS', 'DET']]
# [['Mot', 'derniers'], ['Lemme', 'dernier'], ['POS', 'ADJ']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'surnommant'], ['Lemme', 'surnommant'], ['POS', 'ADJ']]
# [['Mot', '"'], ['Lemme', '"'], ['POS', 'PUNCT']]
# [['Mot', 'Fat'], ['Lemme', 'fat'], ['POS', 'NOUN']]
# [['Mot', 'Cavill"3'], ['Lemme', 'Cavill"3'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'En'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '2000'], ['Lemme', '2000'], ['POS', 'NUM']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'âge'], ['Lemme', 'âge'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', '16'], ['Lemme', '16'], ['POS', 'NUM']]
# [['Mot', 'ans'], ['Lemme', 'an'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'alors'], ['Lemme', 'alors'], ['POS', 'ADV']]
# [['Mot', "qu'"], ['Lemme', 'que'], ['POS', 'SCONJ']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'jouait'], ['Lemme', 'jouer'], ['POS', 'VERB']]
# [['Mot', 'au'], ['Lemme', 'au'], ['POS', 'ADP']]
# [['Mot', 'rugby'], ['Lemme', 'rugby'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'adolescent'], ['Lemme', 'adolescent'], ['POS', 'NOUN']]
# [['Mot', 'rencontre'], ['Lemme', 'rencontr'], ['POS', 'ADJ']]
# [['Mot', 'Russell'], ['Lemme', 'Russell'], ['POS', 'PROPN']]
# [['Mot', 'Crowe'], ['Lemme', 'Crowe'], ['POS', 'PROPN']]
# [['Mot', 'qui'], ['Lemme', 'qui'], ['POS', 'PRON']]
# [['Mot', 'tourne'], ['Lemme', 'tourne'], ['POS', 'VERB']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'ce'], ['Lemme', 'ce'], ['POS', 'DET']]
# [['Mot', 'moment'], ['Lemme', 'moment'], ['POS', 'NOUN']]
# [['Mot', '-là'], ['Lemme', '-là'], ['POS', 'PUNCT']]
# [['Mot', 'son'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'nouveau'], ['Lemme', 'nouveau'], ['POS', 'ADJ']]
# [['Mot', 'film'], ['Lemme', 'film'], ['POS', 'NOUN']]
# [['Mot', "L'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Échange'], ['Lemme', 'Échange'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', "L'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'acteur'], ['Lemme', 'acteur'], ['POS', 'NOUN']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'donne'], ['Lemme', 'donne'], ['POS', 'VERB']]
# [['Mot', 'des'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'conseils'], ['Lemme', 'conseil'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'puis'], ['Lemme', 'pouvoir'], ['POS', 'CCONJ']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'enverra'], ['Lemme', 'envoyer'], ['POS', 'VERB']]
# [['Mot', 'quelques'], ['Lemme', 'quelque'], ['POS', 'DET']]
# [['Mot', 'jours'], ['Lemme', 'jour'], ['POS', 'NOUN']]
# [['Mot', 'plus'], ['Lemme', 'plus'], ['POS', 'ADV']]
# [['Mot', 'tard'], ['Lemme', 'tard'], ['POS', 'ADV']]
# [['Mot', 'un'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'présent'], ['Lemme', 'présent'], ['POS', 'NOUN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Quelques'], ['Lemme', 'quelque'], ['POS', 'DET']]
# [['Mot', 'années'], ['Lemme', 'année'], ['POS', 'NOUN']]
# [['Mot', 'plus'], ['Lemme', 'plus'], ['POS', 'ADV']]
# [['Mot', 'tard'], ['Lemme', 'tard'], ['POS', 'ADV']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'ils'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'tournent'], ['Lemme', 'tourner'], ['POS', 'VERB']]
# [['Mot', 'ensemble'], ['Lemme', 'ensembl'], ['POS', 'ADJ']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'Man'], ['Lemme', 'Man'], ['POS', 'PROPN']]
# [['Mot', 'of'], ['Lemme', 'of'], ['POS', 'PRON']]
# [['Mot', 'Steel4'], ['Lemme', 'steel4'], ['POS', 'PRON']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'Il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'joue'], ['Lemme', 'joue'], ['POS', 'VERB']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'DET']]
# [['Mot', 'nombreuses'], ['Lemme', 'nombreux'], ['POS', 'ADJ']]
# [['Mot', 'pièces'], ['Lemme', 'pièce'], ['POS', 'NOUN']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'comédies'], ['Lemme', 'comédie'], ['POS', 'NOUN']]
# [['Mot', 'musicales'], ['Lemme', 'musical'], ['POS', 'ADJ']]
# [['Mot', 'dont'], ['Lemme', 'dont'], ['POS', 'PRON']]
# [['Mot', 'Le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Songe'], ['Lemme', 'songe'], ['POS', 'NOUN']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'une'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'nuit'], ['Lemme', 'nuit'], ['POS', 'NOUN']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'été'], ['Lemme', 'été'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Grease'], ['Lemme', 'Grease'], ['POS', 'PROPN']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', '40'], ['Lemme', '40'], ['POS', 'NUM']]
# [['Mot', 'Minutes'], ['Lemme', 'minute'], ['POS', 'NOUN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n'], ['Lemme', '\n'], ['POS', 'SPACE']]
# [['Mot', 'Carrière'], ['Lemme', 'Carrière'], ['POS', 'X']]
# [['Mot', '\n'], ['Lemme', '\n'], ['POS', 'SPACE']]
# [['Mot', 'Henry'], ['Lemme', 'Henry'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', 'au'], ['Lemme', 'au'], ['POS', 'ADP']]
# [['Mot', 'festival'], ['Lemme', 'festival'], ['POS', 'NOUN']]
# [['Mot', 'du'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'film'], ['Lemme', 'film'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Tribeca'], ['Lemme', 'Tribeca'], ['POS', 'PROPN']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '2009'], ['Lemme', '2009'], ['POS', 'NUM']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'En'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '2001'], ['Lemme', '2001'], ['POS', 'NUM']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', '18'], ['Lemme', '18'], ['POS', 'NUM']]
# [['Mot', 'ans'], ['Lemme', 'an'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Henry'], ['Lemme', 'Henry'], ['POS', 'PROPN']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', 'fait'], ['Lemme', 'faire'], ['POS', 'VERB']]
# [['Mot', 'ses'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'débuts'], ['Lemme', 'début'], ['POS', 'NOUN']]
# [['Mot', 'professionnels'], ['Lemme', 'professionnel'], ['POS', 'ADJ']]
# [['Mot', 'dans'], ['Lemme', 'dans'], ['POS', 'ADP']]
# [['Mot', 'Laguna'], ['Lemme', 'Laguna'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'À'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'cette'], ['Lemme', 'ce'], ['POS', 'DET']]
# [['Mot', 'occasion'], ['Lemme', 'occasion'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'côtoie'], ['Lemme', 'côtoyer'], ['POS', 'VERB']]
# [['Mot', 'des'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'acteurs'], ['Lemme', 'acteur'], ['POS', 'NOUN']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'expérience'], ['Lemme', 'expérience'], ['POS', 'NOUN']]
# [['Mot', 'comme'], ['Lemme', 'comme'], ['POS', 'ADP']]
# [['Mot', 'Joe'], ['Lemme', 'Joe'], ['POS', 'PROPN']]
# [['Mot', 'Mantegna'], ['Lemme', 'Mantegna'], ['POS', 'PROPN']]
# [['Mot', 'ou'], ['Lemme', 'ou'], ['POS', 'CCONJ']]
# [['Mot', 'encore'], ['Lemme', 'encore'], ['POS', 'ADV']]
# [['Mot', 'Emmanuelle'], ['Lemme', 'Emmanuelle'], ['POS', 'PROPN']]
# [['Mot', 'Seigner'], ['Lemme', 'Seigner'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'tournage'], ['Lemme', 'tournage'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'ce'], ['Lemme', 'ce'], ['POS', 'DET']]
# [['Mot', 'film'], ['Lemme', 'film'], ['POS', 'NOUN']]
# [['Mot', 'reste'], ['Lemme', 'reste'], ['POS', 'VERB']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'un'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'très'], ['Lemme', 'très'], ['POS', 'ADV']]
# [['Mot', 'bon'], ['Lemme', 'bon'], ['POS', 'ADJ']]
# [['Mot', 'souvenir'], ['Lemme', 'souvenir'], ['POS', 'NOUN']]
# [['Mot', 'car'], ['Lemme', 'car'], ['POS', 'CCONJ']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'y'], ['Lemme', 'y'], ['POS', 'PRON']]
# [['Mot', 'tenait'], ['Lemme', 'tenir'], ['POS', 'VERB']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'rôle'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', 'principal'], ['Lemme', 'principal'], ['POS', 'ADJ']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'ce'], ['Lemme', 'ce'], ['POS', 'PRON']]
# [['Mot', 'qui'], ['Lemme', 'qui'], ['POS', 'PRON']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'permit'], ['Lemme', 'permit'], ['POS', 'ADJ']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'développer'], ['Lemme', 'développer'], ['POS', 'VERB']]
# [['Mot', 'une'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'forte'], ['Lemme', 'fort'], ['POS', 'ADJ']]
# [['Mot', 'complicité'], ['Lemme', 'complicité'], ['POS', 'NOUN']]
# [['Mot', 'avec'], ['Lemme', 'avec'], ['POS', 'ADP']]
# [['Mot', 'Dennis'], ['Lemme', 'Dennis'], ['POS', 'PROPN']]
# [['Mot', 'Berry'], ['Lemme', 'Berry'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'réalisateur'], ['Lemme', 'réalisateur'], ['POS', 'NOUN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Mais'], ['Lemme', 'mais'], ['POS', 'CCONJ']]
# [['Mot', "c'"], ['Lemme', 'ce'], ['POS', 'PRON']]
# [['Mot', 'est'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'sa'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'participation'], ['Lemme', 'participation'], ['POS', 'NOUN']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'La'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Vengeance'], ['Lemme', 'vengeance'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Monte'], ['Lemme', 'Monte'], ['POS', 'PROPN']]
# [['Mot', '-'], ['Lemme', '-'], ['POS', 'PROPN']]
# [['Mot', 'Cristo'], ['Lemme', 'Cristo'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', '2002'], ['Lemme', '2002'], ['POS', 'NUM']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'qui'], ['Lemme', 'qui'], ['POS', 'PRON']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'permet'], ['Lemme', 'permettre'], ['POS', 'VERB']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'se'], ['Lemme', 'se'], ['POS', 'PRON']]
# [['Mot', 'révéler'], ['Lemme', 'révéler'], ['POS', 'VERB']]
# [['Mot', 'au'], ['Lemme', 'au'], ['POS', 'ADP']]
# [['Mot', 'grand'], ['Lemme', 'grand'], ['POS', 'ADJ']]
# [['Mot', 'public'], ['Lemme', 'public'], ['POS', 'NOUN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'décroche'], ['Lemme', 'décrocher'], ['POS', 'VERB']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'rôle'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', 'du'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'jeune'], ['Lemme', 'jeune'], ['POS', 'ADJ']]
# [['Mot', 'Albert'], ['Lemme', 'Albert'], ['POS', 'PROPN']]
# [['Mot', 'Mondego'], ['Lemme', 'Mondego'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'fils'], ['Lemme', 'fils'], ['POS', 'NOUN']]
# [['Mot', 'du'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Comte'], ['Lemme', 'comte'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'alors'], ['Lemme', 'alors'], ['POS', 'ADV']]
# [['Mot', "qu'"], ['Lemme', 'que'], ['POS', 'SCONJ']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'est'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'encore'], ['Lemme', 'encore'], ['POS', 'ADV']]
# [['Mot', 'étudiant'], ['Lemme', 'étudier'], ['POS', 'VERB']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'la'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'Stowe'], ['Lemme', 'Stowe'], ['POS', 'PROPN']]
# [['Mot', 'School'], ['Lemme', 'School'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'rôle'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'lequel'], ['Lemme', 'lequel'], ['POS', 'PRON']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'perd'], ['Lemme', 'perdre'], ['POS', 'VERB']]
# [['Mot', 'dix'], ['Lemme', 'dix'], ['POS', 'NUM']]
# [['Mot', 'kilos'], ['Lemme', 'kilo'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'Avant'], ['Lemme', 'avant'], ['POS', 'ADP']]
# [['Mot', 'cette'], ['Lemme', 'ce'], ['POS', 'DET']]
# [['Mot', 'entrée'], ['Lemme', 'entrée'], ['POS', 'NOUN']]
# [['Mot', 'télévisuelle'], ['Lemme', 'télévisuelle'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'auditionne'], ['Lemme', 'auditionner'], ['POS', 'VERB']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'trois'], ['Lemme', 'trois'], ['POS', 'PRON']]
# [['Mot', 'des'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'rôles'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', 'les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'plus'], ['Lemme', 'plus'], ['POS', 'ADV']]
# [['Mot', 'convoités'], ['Lemme', 'convoiter'], ['POS', 'VERB']]
# [['Mot', 'du'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'début'], ['Lemme', 'début'], ['POS', 'NOUN']]
# [['Mot', 'des'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'années'], ['Lemme', 'année'], ['POS', 'NOUN']]
# [['Mot', '2000'], ['Lemme', '2000'], ['POS', 'NUM']]
# [['Mot', ':'], ['Lemme', ':'], ['POS', 'PUNCT']]
# [['Mot', 'Bruce'], ['Lemme', 'Bruce'], ['POS', 'PROPN']]
# [['Mot', 'Wayne'], ['Lemme', 'Wayne'], ['POS', 'PROPN']]
# [['Mot', '/'], ['Lemme', '/'], ['POS', 'PROPN']]
# [['Mot', 'Batman'], ['Lemme', 'Batman'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'Batman'], ['Lemme', 'Batman'], ['POS', 'PROPN']]
# [['Mot', 'Begins'], ['Lemme', 'Begins'], ['POS', 'PROPN']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Clark'], ['Lemme', 'Clark'], ['POS', 'PROPN']]
# [['Mot', 'Kent'], ['Lemme', 'kent'], ['POS', 'ADV']]
# [['Mot', '/'], ['Lemme', '/'], ['POS', 'CCONJ']]
# [['Mot', 'Superman'], ['Lemme', 'Superman'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'Superman'], ['Lemme', 'Superman'], ['POS', 'PROPN']]
# [['Mot', 'Returns'], ['Lemme', 'Returns'], ['POS', 'PROPN']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'James'], ['Lemme', 'James'], ['POS', 'PROPN']]
# [['Mot', 'Bond'], ['Lemme', 'Bond'], ['POS', 'PROPN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'Casino'], ['Lemme', 'Casino'], ['POS', 'PROPN']]
# [['Mot', 'Royale'], ['Lemme', 'Royale'], ['POS', 'PROPN']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', "L'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'histoire'], ['Lemme', 'histoire'], ['POS', 'NOUN']]
# [['Mot', 'retient'], ['Lemme', 'retenir'], ['POS', 'VERB']]
# [['Mot', "qu'"], ['Lemme', 'que'], ['POS', 'PRON']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'échoue'], ['Lemme', 'échouer'], ['POS', 'VERB']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'chaque'], ['Lemme', 'chaque'], ['POS', 'DET']]
# [['Mot', 'fois'], ['Lemme', 'fois'], ['POS', 'NOUN']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'un'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'cheveu'], ['Lemme', 'cheveu'], ['POS', 'NOUN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'ce'], ['Lemme', 'ce'], ['POS', 'PRON']]
# [['Mot', 'qui'], ['Lemme', 'qui'], ['POS', 'PRON']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'vaut'], ['Lemme', 'valoir'], ['POS', 'VERB']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'être'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'nommé'], ['Lemme', 'nommer'], ['POS', 'VERB']]
# [['Mot', 'par'], ['Lemme', 'par'], ['POS', 'ADP']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'magazine'], ['Lemme', 'magazine'], ['POS', 'NOUN']]
# [['Mot', 'britannique'], ['Lemme', 'britannique'], ['POS', 'ADJ']]
# [['Mot', 'Empire'], ['Lemme', 'empire'], ['POS', 'NOUN']]
# [['Mot', '«'], ['Lemme', '«'], ['POS', 'NUM']]
# [['Mot', 'homme'], ['Lemme', 'homme'], ['POS', 'NOUN']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'plus'], ['Lemme', 'plus'], ['POS', 'ADV']]
# [['Mot', 'malchanceux'], ['Lemme', 'malchanceux'], ['POS', 'ADJ']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Hollywood'], ['Lemme', 'Hollywood'], ['POS', 'PROPN']]
# [['Mot', '»'], ['Lemme', '»'], ['POS', 'PUNCT']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'incarner'], ['Lemme', 'incarner'], ['POS', 'VERB']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'héros'], ['Lemme', 'héros'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Gotham'], ['Lemme', 'Gotham'], ['POS', 'PROPN']]
# [['Mot', 'City'], ['Lemme', 'City'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'producteurs'], ['Lemme', 'producteur'], ['POS', 'NOUN']]
# [['Mot', 'lui'], ['Lemme', 'luire'], ['POS', 'PRON']]
# [['Mot', 'préférèrent'], ['Lemme', 'préférer'], ['POS', 'VERB']]
# [['Mot', 'Christian'], ['Lemme', 'Christian'], ['POS', 'PROPN']]
# [['Mot', 'Bale'], ['Lemme', 'bal'], ['POS', 'ADJ']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Brandon'], ['Lemme', 'Brandon'], ['POS', 'PROPN']]
# [['Mot', 'Routh'], ['Lemme', 'Routh'], ['POS', 'PROPN']]
# [['Mot', 'décroche'], ['Lemme', 'décrocher'], ['POS', 'VERB']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'rôle'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'homme'], ['Lemme', 'homme'], ['POS', 'NOUN']]
# [['Mot', "d'"], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'acier'], ['Lemme', 'acier'], ['POS', 'NOUN']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'ses'], ['Lemme', 'son'], ['POS', 'DET']]
# [['Mot', 'dépens'], ['Lemme', 'dépens'], ['POS', 'NOUN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n\n'], ['Lemme', '\n\n'], ['POS', 'SPACE']]
# [['Mot', 'En'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', '2005'], ['Lemme', '2005'], ['POS', 'NUM']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'il'], ['Lemme', 'il'], ['POS', 'PRON']]
# [['Mot', 'fait'], ['Lemme', 'faire'], ['POS', 'VERB']]
# [['Mot', 'partie'], ['Lemme', 'partie'], ['POS', 'NOUN']]
# [['Mot', 'des'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'trois'], ['Lemme', 'trois'], ['POS', 'NUM']]
# [['Mot', 'derniers'], ['Lemme', 'dernier'], ['POS', 'ADJ']]
# [['Mot', 'prétendants'], ['Lemme', 'prétendant'], ['POS', 'NOUN']]
# [['Mot', '('], ['Lemme', '('], ['POS', 'PUNCT']]
# [['Mot', 'les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'deux'], ['Lemme', 'deux'], ['POS', 'NUM']]
# [['Mot', 'autres'], ['Lemme', 'autre'], ['POS', 'ADJ']]
# [['Mot', 'étant'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'Daniel'], ['Lemme', 'Daniel'], ['POS', 'PROPN']]
# [['Mot', 'Craig'], ['Lemme', 'Craig'], ['POS', 'PROPN']]
# [['Mot', 'et'], ['Lemme', 'et'], ['POS', 'CCONJ']]
# [['Mot', 'Sam'], ['Lemme', 'Sam'], ['POS', 'PROPN']]
# [['Mot', 'Worthington'], ['Lemme', 'Worthington'], ['POS', 'PROPN']]
# [['Mot', ')'], ['Lemme', ')'], ['POS', 'PUNCT']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'endosser'], ['Lemme', 'endosser'], ['POS', 'VERB']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'célèbre'], ['Lemme', 'célèbre'], ['POS', 'ADJ']]
# [['Mot', 'smoking'], ['Lemme', 'smoking'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', "l'"], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'agent'], ['Lemme', 'agent'], ['POS', 'NOUN']]
# [['Mot', '007'], ['Lemme', '007'], ['POS', 'NUM']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Martin'], ['Lemme', 'Martin'], ['POS', 'PROPN']]
# [['Mot', 'Campbell'], ['Lemme', 'Campbell'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'réalisateur'], ['Lemme', 'réalisateur'], ['POS', 'NOUN']]
# [['Mot', 'de'], ['Lemme', 'de'], ['POS', 'ADP']]
# [['Mot', 'Casino'], ['Lemme', 'Casino'], ['POS', 'PROPN']]
# [['Mot', 'Royale'], ['Lemme', 'Royale'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'a'], ['Lemme', 'avoir'], ['POS', 'VERB']]
# [['Mot', 'une'], ['Lemme', 'un'], ['POS', 'DET']]
# [['Mot', 'préférence'], ['Lemme', 'préférence'], ['POS', 'NOUN']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'Cavill'], ['Lemme', 'Cavill'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Cependant'], ['Lemme', 'cependant'], ['POS', 'ADV']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'les'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'producteurs'], ['Lemme', 'producteur'], ['POS', 'NOUN']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'trouvent'], ['Lemme', 'trouvent'], ['POS', 'NOUN']]
# [['Mot', 'beaucoup'], ['Lemme', 'beaucoup'], ['POS', 'ADV']]
# [['Mot', 'trop'], ['Lemme', 'trop'], ['POS', 'ADV']]
# [['Mot', 'jeune'], ['Lemme', 'jeune'], ['POS', 'ADJ']]
# [['Mot', 'pour'], ['Lemme', 'pour'], ['POS', 'ADP']]
# [['Mot', 'le'], ['Lemme', 'le'], ['POS', 'DET']]
# [['Mot', 'rôle'], ['Lemme', 'rôle'], ['POS', 'NOUN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Celui'], ['Lemme', 'celui'], ['POS', 'PRON']]
# [['Mot', '-'], ['Lemme', '-'], ['POS', 'PRON']]
# [['Mot', 'ci'], ['Lemme', 'ci'], ['POS', 'PRON']]
# [['Mot', 'revient'], ['Lemme', 'revenir'], ['POS', 'VERB']]
# [['Mot', 'finalement'], ['Lemme', 'finalement'], ['POS', 'ADV']]
# [['Mot', 'à'], ['Lemme', 'à'], ['POS', 'ADP']]
# [['Mot', 'Daniel'], ['Lemme', 'Daniel'], ['POS', 'PROPN']]
# [['Mot', 'Craig'], ['Lemme', 'craig'], ['POS', 'ADJ']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', 'Au'], ['Lemme', 'au'], ['POS', 'ADP']]
# [['Mot', 'départ'], ['Lemme', 'départ'], ['POS', 'NOUN']]
# [['Mot', 'étaient'], ['Lemme', 'être'], ['POS', 'AUX']]
# [['Mot', 'en'], ['Lemme', 'en'], ['POS', 'ADP']]
# [['Mot', 'concours'], ['Lemme', 'concours'], ['POS', 'NOUN']]
# [['Mot', 'Goran'], ['Lemme', 'Goran'], ['POS', 'PROPN']]
# [['Mot', 'Visnjic'], ['Lemme', 'Visnjic'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Julian'], ['Lemme', 'Julian'], ['POS', 'PROPN']]
# [['Mot', 'McMahon'], ['Lemme', 'McMahon'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'James'], ['Lemme', 'James'], ['POS', 'PROPN']]
# [['Mot', 'Purefoy'], ['Lemme', 'Purefoy'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Sam'], ['Lemme', 'Sam'], ['POS', 'PROPN']]
# [['Mot', 'Worthington'], ['Lemme', 'Worthington'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Ewan'], ['Lemme', 'Ewan'], ['POS', 'PROPN']]
# [['Mot', 'McGregor'], ['Lemme', 'McGregor'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Orlando'], ['Lemme', 'Orlando'], ['POS', 'PROPN']]
# [['Mot', 'Bloom'], ['Lemme', 'Bloom'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Christian'], ['Lemme', 'Christian'], ['POS', 'PROPN']]
# [['Mot', 'Bale'], ['Lemme', 'bal'], ['POS', 'ADJ']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Colin'], ['Lemme', 'Colin'], ['POS', 'PROPN']]
# [['Mot', 'Farrell'], ['Lemme', 'Farrell'], ['POS', 'PROPN']]
# [['Mot', ','], ['Lemme', ','], ['POS', 'PUNCT']]
# [['Mot', 'Jude'], ['Lemme', 'Jude'], ['POS', 'PROPN']]
# [['Mot', 'Law'], ['Lemme', 'Law'], ['POS', 'PROPN']]
# [['Mot', 'ou'], ['Lemme', 'ou'], ['POS', 'CCONJ']]
# [['Mot', 'encore'], ['Lemme', 'encore'], ['POS', 'ADV']]
# [['Mot', 'Hugh'], ['Lemme', 'Hugh'], ['POS', 'PROPN']]
# [['Mot', 'Jackman'], ['Lemme', 'Jackman'], ['POS', 'PROPN']]
# [['Mot', '.'], ['Lemme', '.'], ['POS', 'PUNCT']]
# [['Mot', '\n'], ['Lemme', '\n'], ['POS', 'SPACE']]

resultat_norme_moi = [['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'VERB']]
[['POS', 'DET']]
[['POS', 'NUM']]
[['POS', 'NOUN']]
[['POS', 'NUM']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'AUX']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADJ']]
[['POS', 'PUNCT']]
[['POS', 'SPACE']]
[['POS', 'PRON']]
[['POS', 'AUX']]
[['POS', 'ADV']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'CCONJ']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADJ']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'X']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'AUX']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'DET']]
[['POS', 'PROPN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'DET']]
[['POS', 'PRON']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'CCONJ']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PUNCT']]
[['POS', 'PRON']]
[['POS', 'NUM']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'PRON']]
[['POS', 'VERB']]
[['POS', 'ADV']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'PROPN']]
[['POS', 'CCONJ']]
[['POS', 'NOUN']]
[['POS', 'PROPN']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'ADV']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'CCONJ']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PRON']]
[['POS', 'AUX']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'ADJ']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'X']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'SPACE']]
[['POS', 'NOUN']]
[['POS', 'SPACE']]
[['POS', 'PROPN']]
[['POS', 'CCONJ']]
[['POS', 'NOUN']]
[['POS', 'SPACE']]
[['POS', 'ADJ']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'ADJ']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PRON']]
[['POS', 'VERB']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NUM']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'ADP']]
[['POS', 'NOUN']]
[['POS', 'ADJ']]
[['POS', 'PUNCT']]
[['POS', 'ADJ']]
[['POS', 'CCONJ']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'CCONJ']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'ADV']]
[['POS', 'ADP']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'ADJ']]
[['POS', 'ADP']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'ADV']]
[['POS', 'SCONJ']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NUM']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PUNCT']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'CCONJ']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'NUM']]
[['POS', 'PUNCT']]
[['POS', 'PUNCT']]
[['POS', 'PRON']]
[['POS', 'AUX']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADJ']]
[['POS', 'ADJ']]
[['POS', 'PUNCT']]
[['POS', 'PRON']]
[['POS', 'VERB']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADJ']]
[['POS', 'PRON']]
[['POS', 'VERB']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'ADP']]
[['POS', 'ADP']]
[['POS', 'VERB']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'PROPN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'ADP']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'PRON']]
[['POS', 'PRON']]
[['POS', 'VERB']]
[['POS', 'DET']]
[['POS', 'ADJ']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'ADV']]
[['POS', 'SCONJ']]
[['POS', 'NOUN']]
[['POS', 'CCONJ']]
[['POS', 'NOUN']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'NOUN']]
[['POS', 'ADP']]
[['POS', 'DET']]
[['POS', 'NOUN']]
[['POS', 'PUNCT']]
[['POS', 'DET']]
[['POS', 'ADJ']]
[['POS', 'DET']]
[['POS', 'ADJ']]
[['POS', 'PUNCT']]
[['POS', 'NOUN']]
[['POS', 'PROPN']]
[['POS', 'PUNCT']]
[['POS', 'SPACE']]